# Basic Neural Network Using Keras

### Import the required modules and read the "iris" dataset

In [29]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from keras.optimizers import SGD, Adam


iris = pd.read_csv("data/iris.csv")
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [30]:
seed = 10
np.random.seed(seed)

In [31]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [32]:
iris.shape

(150, 6)

In [33]:
iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

### Split the dataset into input variables (X) and the output class variable (Y). And also split the data into training and test tests

In [34]:
X = iris.iloc[:,1:5].values
y = iris.iloc[:,5].values

encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=0) 

### Define a simple Neural Network Model with 1 hidden layer
Keras has its layers as a sequence. So, we create a Sequential model and add layers one at a time. As there are 4 input variables, we specify the argument "input_shape" as 4. Then we can add as many hidden layers as the problem demands. Since this is a simple datset, I expect to get a good accuracy with just a single hidden layer.<br>

We use a fully-connected network, which is defined by "Dense" class. The number of neurons in the layer is given as the first argument and specify the activation function using the activation argument.<br>

We use the rectifier ('relu') activation function on the first two layers and a sigmoid activation function in the output layer. It seems better performance is achieved using the 'relu' activation function. We use a sigmoid on the output layer so that the output is between 0 and 1.<br>

In [35]:
model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))

### Compile the Model

There are numerical libraries such as Theano or TensorFlow for the compilation of the model I used TensorFlow. There are certain additional parameters that we need to specify, such as, the loss function (to evaluate a set of weights), the optimizer (to search through different weights for the network) and also optional metrics that we like to collect.<br>

I used the loss function "binary_crossentropy" and the gradient descent algorithm "adam". Finally, as it is a classification problem, "accuracy" is used as the metric.

In [36]:
model.compile(optimizer=Adam(lr=0.04), loss='categorical_crossentropy', metrics=['accuracy'])

### Summary of the Model

This just gives the summary of the model, with parameters in each layer. There are a total of 165 parameters in the eural network model chosen.

In [37]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27        
Total params: 165
Trainable params: 165
Non-trainable params: 0
_________________________________________________________________


### Fit the Model

We have defined our model and also compiled it. Noe, we execute the model on the data. We can train our model on the dataset by using fit() function. Here, we specify a parameter called "epochs", which are number of iterations that the model needs to undergo. The training process runs for for a fixed number of iterations, here, I specified it to be 100.<br>

There areother parameters. such as the "batch_size". Whe not specified, it takes the default value of 32. These parameters can be chosen by trial and error.

In [38]:
model.fit(X_train, y_train, epochs=100)

y_pred = model.predict(X_test)


Epoch 1/100
120/120 [==============================] - 1s 4ms/step - loss: 1.0830 - acc: 0.5083
Epoch 2/100
120/120 [==============================] - 0s 50us/step - loss: 0.7974 - acc: 0.6917
Epoch 3/100
120/120 [==============================] - 0s 58us/step - loss: 0.6402 - acc: 0.7167
Epoch 4/100
120/120 [==============================] - 0s 58us/step - loss: 0.5201 - acc: 0.6917
Epoch 5/100
120/120 [==============================] - 0s 58us/step - loss: 0.4456 - acc: 0.6917
Epoch 6/100
120/120 [==============================] - 0s 67us/step - loss: 0.4224 - acc: 0.7500
Epoch 7/100
120/120 [==============================] - 0s 58us/step - loss: 0.4062 - acc: 0.7250
Epoch 8/100
120/120 [==============================] - 0s 67us/step - loss: 0.3913 - acc: 0.7583
Epoch 9/100
120/120 [==============================] - 0s 58us/step - loss: 0.3619 - acc: 0.8667
Epoch 10/100
120/120 [==============================] - 0s 58us/step - loss: 0.2976 - acc: 0.9333
Epoch 11/100
120/120 [========

120/120 [==============================] - 0s 58us/step - loss: 0.0734 - acc: 0.9750
Epoch 85/100
120/120 [==============================] - 0s 58us/step - loss: 0.0595 - acc: 0.9750
Epoch 86/100
120/120 [==============================] - 0s 67us/step - loss: 0.0771 - acc: 0.9667
Epoch 87/100
120/120 [==============================] - 0s 50us/step - loss: 0.0606 - acc: 0.9833
Epoch 88/100
120/120 [==============================] - 0s 58us/step - loss: 0.0656 - acc: 0.9750
Epoch 89/100
120/120 [==============================] - 0s 75us/step - loss: 0.0779 - acc: 0.9583
Epoch 90/100
120/120 [==============================] - 0s 75us/step - loss: 0.0953 - acc: 0.9500
Epoch 91/100
120/120 [==============================] - 0s 58us/step - loss: 0.0926 - acc: 0.9500
Epoch 92/100
120/120 [==============================] - 0s 58us/step - loss: 0.0916 - acc: 0.9667
Epoch 93/100
120/120 [==============================] - 0s 58us/step - loss: 0.0858 - acc: 0.9667
Epoch 94/100
120/120 [===========

In [39]:
y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

In [40]:
y_test

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [41]:
y_pred

array([[  1.76730172e-14,   1.86062360e-03,   9.98139381e-01],
       [  1.37740353e-04,   9.99671459e-01,   1.90780149e-04],
       [  9.99998093e-01,   1.91132995e-06,   3.13139419e-21],
       [  2.88519175e-14,   2.14016065e-03,   9.97859895e-01],
       [  9.99971032e-01,   2.90222124e-05,   5.85725558e-18],
       [  1.16998213e-16,   4.43517871e-04,   9.99556482e-01],
       [  9.99981761e-01,   1.82118692e-05,   1.78407266e-18],
       [  8.30872523e-07,   9.96442616e-01,   3.55650019e-03],
       [  7.51322773e-07,   9.92935836e-01,   7.06345914e-03],
       [  4.36771588e-05,   9.99805033e-01,   1.51328422e-04],
       [  1.09239987e-11,   1.48574570e-02,   9.85142529e-01],
       [  1.65262747e-06,   9.98161614e-01,   1.83677475e-03],
       [  1.35341975e-06,   9.90882277e-01,   9.11644660e-03],
       [  5.23167216e-07,   9.86147344e-01,   1.38521995e-02],
       [  2.92066488e-07,   9.64065552e-01,   3.59341316e-02],
       [  9.99951959e-01,   4.80689851e-05,   2.4255433

In [42]:
y_test_class

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [43]:
y_pred_class

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 2, 0, 0, 1, 1, 0], dtype=int64)

### Accuracy of the predicted values

In [24]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        13
          2       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


### Evaluate the Model

We trained the neural network on the train dataset and evaluate its performance on the test dataset. This generates a prediction for each input and output pair and collect scores, including the average loss and any metrics we configured, such as accuracy.<br>

We got an accuracy of 100% on the test dataset, which is reiterated from the above evaluation.

In [25]:
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

30/30 [==============================] - 0s 2ms/step

acc: 100.00%


### References
https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/